import type { MetadataRoute } from "next";
import { SITE_DESCRIPTION, SITE_NAME } from "@/lib/siteUrl";

/**
 * Served at /manifest.webmanifest; Next injects the <link rel="manifest"> tag
 * automatically. Its only job is to give Android a real home-screen icon --
 * without a manifest, Chrome's "Add to Home screen" falls back to the favicon,
 * which is how the site ended up wearing the stock create-next-app mark.
 *
 * `display: "browser"` is deliberate: tapping the saved icon opens a normal
 * browser tab with the URL bar, exactly as it does today. Switching to
 * "standalone" would turn this into an installable PWA (fullscreen, its own
 * task-switcher entry, an "Install app" prompt) -- a UX change well beyond
 * fixing the icon, and an awkward one for a wiki whose links get shared out.
 * app/layout.tsx's `appleWebApp` omits `capable` for the same reason.
 *
 * Icons point at static files under public/icons/ rather than the app/icon.png
 * file convention, because that convention is served from a content-hashed URL
 * (/icon?<generated>) that this hand-written JSON can't reference stably.
 * All of them are generated by scripts/generate-app-icons.ts.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: SITE_NAME,
    // Android truncates the label under the icon; the full name doesn't fit.
    short_name: "Israel Programs",
    description: SITE_DESCRIPTION,
    start_url: "/",
    display: "browser",
    background_color: "#1a2740",
    theme_color: "#1a2740",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      // Android crops this one to a circle, so it carries extra padding -- the
      // "any" icons above would lose the star's points under that mask.
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
