/**
 * Read-only report: finds `--` used as an em dash and straight quotes/apostrophes in
 * Program.description and PollQuestion.text/labels/QuestionBucket.name/description --
 * the fields style guide item 13 explicitly says NOT to sweep or modify here (question
 * content is frozen by standing rule 3; program descriptions are flagged for the site
 * owner to fix by hand rather than auto-edited).
 *
 * MODIFIES NOTHING. Run:
 *   set -a && source .env && source .env.local && set +a
 *   npx tsx scripts/scan-db-typography.ts > research/typography-db-report-2026-07-30.md
 */
import { PrismaClient } from "../app/generated/prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";

const adapter = new PrismaPg(process.env.DATABASE_URL!);
const prisma = new PrismaClient({ adapter });

const DOUBLE_HYPHEN = /\S\s*--\s*\S/;
const STRAIGHT_QUOTE = /['"]/;

function flags(s: string | null | undefined): { dd: boolean; sq: boolean } {
  if (!s) return { dd: false, sq: false };
  return { dd: DOUBLE_HYPHEN.test(s), sq: STRAIGHT_QUOTE.test(s) };
}

async function main() {
  const lines: string[] = [];
  lines.push("# DB typography report");
  lines.push("");
  lines.push(
    "Read-only scan for `--` used as an em dash and straight quotes/apostrophes, per style guide item 13. Generated by `scripts/scan-db-typography.ts` -- nothing here was written back to the database. Question text/labels/bucket names are frozen (standing rule 3); Program.description is out of scope for this task's automated sweep. Both are listed here for hand-editing."
  );
  lines.push("");

  // Program.description
  const programs = await prisma.program.findMany({
    select: { id: true, slug: true, name: true, description: true },
    orderBy: { name: "asc" },
  });
  const flaggedPrograms = programs
    .map((p) => ({ ...p, ...flags(p.description) }))
    .filter((p) => p.dd || p.sq);

  lines.push(`## Program.description (${flaggedPrograms.length} of ${programs.length} rows flagged)`);
  lines.push("");
  lines.push("| Slug | -- | Straight quote | Description |");
  lines.push("|---|---|---|---|");
  for (const p of flaggedPrograms) {
    const desc = (p.description ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
    lines.push(`| ${p.slug} | ${p.dd ? "yes" : ""} | ${p.sq ? "yes" : ""} | ${desc} |`);
  }
  lines.push("");

  // PollQuestion.text + labels
  const questions = await prisma.pollQuestion.findMany({
    select: { id: true, key: true, text: true, labels: true, status: true },
    orderBy: { key: "asc" },
  });
  const flaggedQuestions = questions
    .map((q) => {
      const textFlags = flags(q.text);
      const labelFlags = q.labels.map(flags);
      const dd = textFlags.dd || labelFlags.some((f) => f.dd);
      const sq = textFlags.sq || labelFlags.some((f) => f.sq);
      return { ...q, dd, sq };
    })
    .filter((q) => q.dd || q.sq);

  lines.push(`## PollQuestion.text + labels (${flaggedQuestions.length} of ${questions.length} ACTIVE+RETIRED rows flagged)`);
  lines.push("");
  lines.push("| Key | Status | -- | Straight quote | Text | Labels |");
  lines.push("|---|---|---|---|---|---|");
  for (const q of flaggedQuestions) {
    const text = q.text.replace(/\|/g, "\\|");
    const labels = q.labels.join(" / ").replace(/\|/g, "\\|");
    lines.push(`| ${q.key} | ${q.status} | ${q.dd ? "yes" : ""} | ${q.sq ? "yes" : ""} | ${text} | ${labels} |`);
  }
  lines.push("");

  // QuestionBucket.name + description
  const buckets = await prisma.questionBucket.findMany({
    select: { id: true, name: true, description: true, status: true },
    orderBy: { name: "asc" },
  });
  const flaggedBuckets = buckets
    .map((b) => {
      const nameFlags = flags(b.name);
      const descFlags = flags(b.description);
      return { ...b, dd: nameFlags.dd || descFlags.dd, sq: nameFlags.sq || descFlags.sq };
    })
    .filter((b) => b.dd || b.sq);

  lines.push(`## QuestionBucket.name + description (${flaggedBuckets.length} of ${buckets.length} rows flagged)`);
  lines.push("");
  if (flaggedBuckets.length === 0) {
    lines.push("None flagged.");
  } else {
    lines.push("| Name | Status | -- | Straight quote | Description |");
    lines.push("|---|---|---|---|---|");
    for (const b of flaggedBuckets) {
      const desc = (b.description ?? "").replace(/\|/g, "\\|").replace(/\n/g, " ");
      lines.push(`| ${b.name} | ${b.status} | ${b.dd ? "yes" : ""} | ${b.sq ? "yes" : ""} | ${desc} |`);
    }
  }
  lines.push("");

  console.log(lines.join("\n"));
  await prisma.$disconnect();
}

main();
