-- Adds the explicit-submit timestamp for the rating form's new "Submit ratings" button.
--
-- Additive and nullable by design: null means "never pressed submit", which is the correct
-- reading for every response predating this column. No backfill, no default, no table
-- rewrite -- so this is safe to apply to production BEFORE the code that writes it ships
-- (the code-last ordering rule in CLAUDE.md).
--
-- `submittedAt` is deliberately orthogonal to `status`. Submitting never touches
-- status/flags/verified/answers, so it cannot change what counts toward unlock. Never add
-- `submittedAt IS NOT NULL` to a public-math gate -- every pre-existing row is null and
-- would silently drop out of every published score.
--
-- Hand-written rather than generated by `prisma migrate dev`: this repo's .env points at
-- production, and `prisma db push` must never be run against this schema (it silently drops
-- the hand-added CHECK constraints and partial indexes on the poll tables).

-- AlterTable
ALTER TABLE "PollResponse" ADD COLUMN     "submittedAt" TIMESTAMP(3);
